dist: trusty
sudo: required
language: scala
scala:
- 2.11.8
script:
  - sbt test it:test
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
addons:
  apt:
    sources:
      - mongodb-3.2-precise
     packages:
       - mongodb-org-server
install:
    - sudo apt-get install -y --allow-downgrades mongodb-org=3.2.18
